version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - "25565:25565"
    environment:
      TYPE: "AIRPLANE"
      VERSION: "LATEST"
      EULA: "TRUE"
      MOTD: "3 months"
      DIFFICULTY: "hard"
      MAX_PLAYERS: "20"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MAX_TICK_TIME: "-1"
    volumes:
      - ~/minecraft-data:/data
    restart: unless-stopped