FROM ubuntu:latest

RUN apt update -y
RUN apt upgrade -y
RUN apt install python3 python3-pip git -y

RUN pip install aiohttp
RUN pip insatll websockets

WORKDIR /root
RUN git clone https://github.com/Chicoyaki01/Discord
ADD start.sh /root/Discord
ADD token /root/Discord

WORKDIR /root/Discord

CMD sh start.sh