FROM ubuntu:latest

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install python3 python3-pip git -y

RUN pip install aiohttp websockets

WORKDIR /root
RUN git clone https://github.com/Chicoyaki01/Discord
ADD start.sh /root/Discord
ADD token /root/Discord

WORKDIR /root/Discord

CMD sh start.sh